### ISSUE TITLE
已失效

### ISSUE THREAD

**Issue by mullyong** [Nanomoa/CozeDiscord#2]
已失效。

**Comment by bobolehe** [comment]
您指的失效是哪一部分？

**Comment by Nanomoa** [comment]
可能是因为国内网络无法请求到 discord 服务器，需要代理

**Comment by mullyong** [comment]
> 可能是因为国内网络无法请求到不一致服务器，需要代理

coze bot无法接收discord bot的消息。

**Comment by Nanomoa** [comment]
> > 可能是因为国内网络无法请求到不一致服务器，需要代理
> 
> coze bot无法接收discord bot的消息。

对的，我在Issue3中提到了，早上没有发现这个问题，现在正在修
